---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-web-app
  labels:
    app: nodejs-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-web-app
  template:
    metadata:
      labels:
        app: nodejs-web-app
    spec:
      containers:
      - name: nodejs-web-app
        image: nbkhoi/nodejs-web-app
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000