apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
 # Service name
 name: nodejs-web-app
 labels:
    app: nodejs-web-app
spec:
 selector:
   # Selector for Pods
   app: nodejs-web-app
 ports:
   # Port Map
 - port: 80
   targetPort: 3000
   protocol: TCP
 type: LoadBalancer